# Generated by Django 3.2.23 on 2024-01-04 16:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImageServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_base', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('pid', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('collections', models.ManyToManyField(blank=True, related_name='manifests', to='iiif.Collection')),
                ('image_server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iiif.imageserver')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iiif.manifest')),
            ],
        ),
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('ocr_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('image_server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iiif.imageserver')),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='iiif.manifest')),
            ],
        ),
    ]
