# Generated by Django 3.2.23 on 2024-01-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiif', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='canvas',
            name='width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
