# Generated by Django 3.2.23 on 2024-01-24 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iiif', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='iiif.canvas')),
            ],
        ),
    ]
