# Generated by Django 3.2.23 on 2024-03-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiif', '0002_alter_manifest_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
    ]
