# Generated by Django 3.2.23 on 2024-01-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiif', '0002_auto_20240110_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
