# Generated by Django 3.2.23 on 2024-01-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiif', '0002_ocr'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocr',
            name='content',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='ocr',
            name='h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ocr',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ocr',
            name='resource_type',
            field=models.CharField(choices=[('cnt:ContentAsText', 'ocr'), ('dctypes:Text', 'text')], default='dctypes:Text', max_length=50),
        ),
        migrations.AddField(
            model_name='ocr',
            name='w',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ocr',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ocr',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
