# Generated by Django 3.2.23 on 2024-04-24 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iiif', '0003_auto_20240325_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='image_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iiif.imageserver'),
        ),
    ]
