# Generated by Django 3.2.23 on 2024-01-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiif', '0003_auto_20240125_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='default_ocr',
            field=models.CharField(choices=[('word', 'word'), ('line', 'line'), ('both', 'both')], default='word', max_length=30),
        ),
    ]
