# Generated by Django 3.2.23 on 2024-05-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiif', '0004_canvas_image_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='resource',
            field=models.TextField(blank=True, null=True),
        ),
    ]
