# Generated by Django 3.2.23 on 2024-01-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiif', '0004_canvas_default_ocr'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageserver',
            name='storage_service',
            field=models.CharField(default='local', max_length=25),
        ),
    ]
