# Generated by Django 3.2.23 on 2025-01-08 13:08

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("iiif", "0005_canvas_resource"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="manifest",
            name="languages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Languages present in the manifest.",
                to="iiif.Language",
            ),
        ),
    ]
