# Generated by Django 3.2.23 on 2025-01-16 20:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iiif', '0006_auto_20250108_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='pid',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
