# Generated by Django 3.2.23 on 2025-03-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiif', '0007_alter_canvas_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='published_date',
            field=models.CharField(blank=True, help_text='Used for display only.', max_length=255, null=True, verbose_name='Published date (display)'),
        ),
    ]
