# Generated by Django 3.2.25 on 2025-03-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iiif', '0008_manifest_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='start_canvas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_canvas', to='iiif.canvas'),
        ),
    ]
