# Generated by Django 3.2.25 on 2025-03-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiif', '0009_manifest_start_canvas'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
    ]
