# Generated by Django 3.2.25 on 2025-06-23 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iiif.models
import iiif.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iiif', '0010_collection_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('w', models.IntegerField(default=0)),
                ('h', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('content', models.TextField(blank=True, default=' ', null=True)),
                ('resource_type', models.CharField(choices=[('cnt:ContentAsText', 'ocr'), ('dctypes:Text', 'text')], default='dctypes:Text', max_length=50)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='iiif.canvas')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('pid', models.CharField(default=iiif.utils.encode_noid, help_text="Unique ID. Do not use _'s or spaces in the pid.", max_length=255)),
                ('label', models.CharField(default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('w', models.IntegerField(default=0)),
                ('h', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('content', models.TextField(blank=True, default=' ', null=True)),
                ('raw_content', models.TextField(blank=True, default=' ', null=True)),
                ('resource_type', models.CharField(choices=[('cnt:ContentAsText', 'ocr'), ('dctypes:Text', 'text')], default='dctypes:Text', max_length=50)),
                ('motivation', models.CharField(choices=[('oa:commenting', 'commenting'), ('sc:painting', 'painting')], default='sc:painting', max_length=50)),
                ('purpose', models.CharField(choices=[('AS', 'Assessing'), ('BM', 'Bookmarking'), ('CL', 'Classifying'), ('CM', 'Commenting'), ('DS', 'Describing'), ('ED', 'Editing'), ('HL', 'Highlighting'), ('ID', 'Identifying'), ('LK', 'Linking'), ('MO', 'Moderating'), ('PT', 'Painting'), ('QT', 'Questioning'), ('RE', 'Replying'), ('SP', 'Supplementing'), ('TG', 'Tagging')], default=iiif.models.AnnotationPurpose['supplementing'], max_length=2)),
                ('primary_selector', models.CharField(choices=[('FR', 'Fragmentselector'), ('CS', 'Cssselector'), ('XP', 'Xpathselector'), ('TQ', 'Textquoteselector'), ('TP', 'Textpositionselector'), ('DP', 'Datapositionselector'), ('SV', 'Svgselector'), ('RG', 'Rangeselector')], default=iiif.models.AnnotationSelector['FragmentSelector'], max_length=2)),
                ('format', models.CharField(choices=[('text/plain', 'plain text'), ('text/html', 'html')], default='text/plain', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('oa_annotation', models.JSONField(default=dict)),
                ('svg', models.TextField(blank=True, null=True)),
                ('style', models.CharField(blank=True, max_length=1000, null=True)),
                ('canvas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iiif.canvas')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
