# Generated by Django 3.2.23 on 2024-05-08 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import readux_ingest_ecds.models
import readux_ingest_ecds.storages
import uuid

Manifest = settings.IIIF_MANIFEST_MODEL
ImageServer = settings.IIIF_IMAGE_SERVER_MODEL
Collection = settings.IIIF_COLLECTION_MODEL

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('bundle', models.FileField(blank=True, null=True, storage=readux_ingest_ecds.storages.TmpStorage, upload_to=readux_ingest_ecds.models.local_tmp)),
                ('collections', models.ManyToManyField(blank=True, help_text='Optional: Collections to attach to the volume ingested in this form.', related_name='ecds_ingest_collections', to=Collection)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecds_ingest_created_locals', to=settings.AUTH_USER_MODEL)),
                ('image_server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecds_ingest_image_server', to=ImageServer)),
                ('manifest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecds_ingest_manifest', to=Manifest)),
                ('bundle_path', models.CharField(blank=True, max_length=1000)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Local',
            },
        ),
        migrations.CreateModel(
            name='Bulk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collections', models.ManyToManyField(blank=True, help_text='Optional: Collections to attach to the volume ingested in this form.', related_name='ecds_bulk_ingest_collections', to=Collection)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecds_bulk_ingest_created_locals', to=settings.AUTH_USER_MODEL)),
                ('image_server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecds_bulk_ingest_image_server', to=ImageServer)),
                ('volume_files', models.FileField(null=True, storage=readux_ingest_ecds.storages.TmpStorage, upload_to=readux_ingest_ecds.models.bulk_path)),
            ],
            options={
                'verbose_name_plural': 'Bulk',
            },
        ),
    ]
