# Generated by Django 3.2.23 on 2024-01-11 18:25

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion

Manifest = settings.IIIF_MANIFEST_MODEL
ImageServer = settings.IIIF_IMAGE_SERVER_MODEL
Collection = settings.IIIF_COLLECTION_MODEL

class Migration(migrations.Migration):

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('bundle', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='tmp'), upload_to='')),
                ('collections', models.ManyToManyField(blank=True, help_text='Optional: Collections to attach to the volume ingested in this form.', related_name='ecds_ingest_collections', to=Collection)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecds_ingest_created_locals', to=settings.AUTH_USER_MODEL)),
                ('image_server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecds_ingest_image_server', to=ImageServer)),
                ('manifest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecds_ingest_manifest', to=Manifest)),
            ],
            options={
                'verbose_name_plural': 'Local',
            },
        ),
    ]
