# Generated by Django 3.2.23 on 2024-07-19 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readux_ingest_ecds', '0001_squashed_0005_alter_bulk_volume_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='bulk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='readux_ingest_ecds.bulk'),
        ),
    ]
