# Generated by Django 3.2.23 on 2024-02-01 14:06

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import readux_ingest_ecds.models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('readux_ingest_ecds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='tmp'), upload_to=readux_ingest_ecds.models.bulk_path)),
            ],
        ),
        migrations.AddField(
            model_name='local',
            name='bundle_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='Bulk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collections', models.ManyToManyField(blank=True, help_text='Optional: Collections to attach to the volume ingested in this form.', related_name='ecds_bulk_ingest_collections', to='iiif.Collection')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecds_bulk_ingest_created_locals', to=settings.AUTH_USER_MODEL)),
                ('image_server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecds_bulk_ingest_image_server', to='iiif.imageserver')),
                ('volume_files', models.ManyToManyField(blank=True, to='readux_ingest_ecds.VolumeFile')),
            ],
            options={
                'verbose_name_plural': 'Bulk',
            },
        ),
    ]
