# Generated by Django 3.2.23 on 2024-07-19 14:00

from django.db import migrations, models
import readux_ingest_ecds.models
import readux_ingest_ecds.storages


class Migration(migrations.Migration):

    dependencies = [
        ('readux_ingest_ecds', '0002_local_bulk'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulk',
            name='metadata_file',
            field=models.FileField(null=True, storage=readux_ingest_ecds.storages.TmpStorage, upload_to=readux_ingest_ecds.models.bulk_path),
        ),
    ]
