# Generated by Django 3.2.23 on 2024-03-13 17:37

from django.db import migrations, models
import readux_ingest_ecds.models
import readux_ingest_ecds.storages
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('readux_ingest_ecds', '0002_auto_20240201_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='local',
            name='bundle',
            field=models.FileField(blank=True, null=True, storage=readux_ingest_ecds.storages.TmpStorage, upload_to=readux_ingest_ecds.models.local_tmp),
        ),
    ]
