# Generated by Django 3.2.23 on 2024-03-13 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('readux_ingest_ecds', '0003_auto_20240313_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='local',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
