# Generated by Django 3.2.23 on 2024-03-14 19:39

from django.db import migrations, models
import readux_ingest_ecds.models
import readux_ingest_ecds.storages


class Migration(migrations.Migration):

    dependencies = [
        ('readux_ingest_ecds', '0004_auto_20240313_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulk',
            name='volume_files',
            field=models.FileField(null=True, storage=readux_ingest_ecds.storages.TmpStorage, upload_to=readux_ingest_ecds.models.bulk_path),
        ),
    ]
