# Generated by Django 3.2.23 on 2024-12-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readux_ingest_ecds', '0005_local_warnings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s3ingest',
            options={'verbose_name_plural': 'S3 Ingests'},
        ),
        migrations.AddField(
            model_name='s3ingest',
            name='prefix',
            field=models.CharField(blank=True, help_text='Optional: The name of a subdirectory in the bucket. This will limit where the ingest will look for files.', max_length=255, null=True),
        ),
    ]
