# Generated by Django 3.2.23 on 2025-01-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readux_ingest_ecds', '0006_auto_20241211_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='from_s3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='local',
            name='prefix',
            field=models.CharField(blank=True, help_text='Optional: The name of a subdirectory in the bucket. This will limit where the ingest will look for files.', max_length=255, null=True),
        ),
    ]
