# Generated by Django 3.2.23 on 2025-01-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readux_ingest_ecds', '0007_auto_20250116_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='source_bucket',
            field=models.CharField(blank=True, help_text='Only from used when creating from S3Ingest.', max_length=255, null=True),
        ),
    ]
