# Generated by Django 3.2.23 on 2025-03-03 16:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("readux_ingest_ecds", "0008_local_source_bucket"),
    ]

    operations = [
        migrations.CreateModel(
            name="Remote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        help_text="URL for remote IIIF manifest.", max_length=500
                    ),
                ),
                (
                    "image_server",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="ecds_remote_ingest_image_server",
                        to="iiif.imageserver",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="local",
            name="from_s3",
            field=models.BooleanField(
                default=False, help_text="Only from used when creating from S3Ingest."
            ),
        ),
        migrations.AlterField(
            model_name="local",
            name="prefix",
            field=models.CharField(
                blank=True,
                help_text="Only from used when creating from S3Ingest.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RemoteAnnotationPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        help_text="URL for remote IIIF annotation page.", max_length=500
                    ),
                ),
                (
                    "ingest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="readux_ingest_ecds.remote",
                    ),
                ),
            ],
        ),
    ]
