# Generated by Django 3.2.25 on 2025-03-03 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iiif', '0008_manifest_published_date'),
        ('readux_ingest_ecds', '0009_auto_20250303_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='remote',
            name='manifest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecds_remote_ingest_manifest', to='iiif.manifest'),
        ),
    ]
