# Generated by Django 3.2.25 on 2025-03-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readux_ingest_ecds', '0010_remote_manifest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulk',
            options={'verbose_name': 'Bulk Ingest', 'verbose_name_plural': 'Bulk Ingests'},
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name': 'Local Ingest', 'verbose_name_plural': 'Local Ingests'},
        ),
        migrations.AlterModelOptions(
            name='remote',
            options={'verbose_name': 'Remote Ingest', 'verbose_name_plural': 'Remote Ingests'},
        ),
        migrations.AlterModelOptions(
            name='s3ingest',
            options={'verbose_name': 'S3 Ingest', 'verbose_name_plural': 'S3 Ingests'},
        ),
    ]
