# Generated by Django 3.2.25 on 2025-03-07 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readux_ingest_ecds', '0011_auto_20250307_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='remote',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecds_ingest_created_remote', to=settings.AUTH_USER_MODEL),
        ),
    ]
