# Generated by Django 3.2.25 on 2025-07-31 13:49

from django.db import migrations, models
from django.conf import settings

Collection = settings.IIIF_COLLECTION_MODEL


class Migration(migrations.Migration):

    dependencies = [
        ("readux_ingest_ecds", "0012_remote_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remote",
            name="link",
            field=models.TextField(
                help_text="URL for remote IIIF manifest.", max_length=500
            ),
        ),
        # AlterField on a ManyToManyField calls m2m_reverse_field_name() internally,
        # which was removed in Django 5.0. Since changing help_text/related_name on a
        # M2M field doesn't touch the database schema at all, we only need to update
        # the migration state — no actual SQL needs to run.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="s3ingest",
                    name="collections",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="Optional: Collections to attach to ALL volumes ingested in this form.",
                        related_name="ecds_ingest_collections_s3",
                        to=Collection,
                    ),
                ),
            ],
        ),
    ]
