# Generated by Django 3.2.25 on 2025-07-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readux_ingest_ecds", "0012_remote_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remote",
            name="link",
            field=models.TextField(
                help_text="URL for remote IIIF manifest.", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="s3ingest",
            name="collections",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional: Collections to attach to ALL volumes ingested in this form.",
                related_name="ecds_ingest_collections_s3",
                to="iiif.Collection",
            ),
        ),
    ]
