name: CI

on:
  push:
    branches:
      - develop
      - main
env:
  DJANGO_ENV: test

jobs:
  pytest:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          cd test_app
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          cd test_app
          python manage.py makemigrations readux_ingest_ecds
          python manage.py migrate

      - name: Run Tests
        run: |
          cd test_app
          pytest tests/
